### ISSUE TITLE
.osx problem setting default desktop background

### ISSUE THREAD

**Issue by bioteamMichael** [geerlingguy/dotfiles#7]
It looks like with newer versions of OS X (I'm on Mojave, 10.14.6) the desktop background you've got in the script no longer exists. When you run the line to update the background the Dock gets stuck in a loop where it's constantly crashing with an error that looks very similar to this one:

```
2018-08-18 22:05:31.276 Dock[1061:44244] -[__NSCFNumber stringByExpandingTildeInPath]: unrecognized selector sent to instance 0xe5cdf6a4f4b8bcfb
2018-08-18 22:05:31.277 Dock[1061:44244] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber stringByExpandingTildeInPath]: unrecognized selector sent to instance 0xe5cdf6a4f4b8bcfb
```

```
# michael @ xanadu in ~ [11:20:53]
$ ls /Library/Desktop\ Pictures/Solid\ Colors
 Black.png         'Dusty Rose.png'      Gold.png   'Red Orange.png'  'Soft Pink.png'        Stone.png              Yellow.png
'Blue Violet.png'  'Electric Blue.png'   Ocher.png  'Rose Gold.png'   'Space Gray Pro.png'   Teal.png
 Cyan.png          'Gold 2.png'          Plum.png    Silver.png       'Space Gray.png'      'Turquoise Green.png'
```

**Comment by geerlingguy** [comment]
Yeah; and the method for setting it is different now too; I fixed this in https://github.com/geerlingguy/dotfiles/commit/40aac0f567170aab56c83617ef7ef2c0e103dc2d#diff-2b619e5c7c5c228b886e968419fa8db6e3b1edf59d51ec1cd983685aa4869682R55

Thanks for bringing it to my attention though ;)
